version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Aa@123456"
    ports:
      - "1433:1433"
  web-api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
